# Site settings
title: GalenLin
email: oolgloo.2012@gmail.com
description: Talk about android, iOS, html and tools for app development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://galenlin.github.io" # the base hostname & protocol for your site
weibo_username: galenlin
github_username:  galenlin

# Build settings
# Github markdown style
highlighter: true
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
